git:
  depth: 2
sudo: required
services:
  - docker
language: node_js
node_js: node
cache:
  directories:
    - $HOME/.rocker-cache
    - $HOME/docker/

env:
  global:
    - DOCKER_CACHE_FILE=$HOME/docker/cache.tar.gz

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker login -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD" quay.io
  - if [ -f ${DOCKER_CACHE_FILE} ]; then gunzip -c ${DOCKER_CACHE_FILE} | docker load; fi
  - docker pull docker/compose:1.9.0
  - docker pull withinboredom/rocker:latest

install:
  - npm install -g tyche

script:
  - tyche bump --set $TRAVIS_BRANCH
  - if [[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then mkdir -p $(dirname ${DOCKER_CACHE_FILE}) ; docker save $(docker history -q ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} | grep -v '<missing>') | gzip > ${DOCKER_CACHE_FILE}; fi