version: '3'
services:
  api-builder:
    image: withinboredom/yarn:latest
    volumes:
      - ./src/api:/app/api
      - api_modules:/app/api/node_modules
    command: bash -c "cd /app/api && yarn"
    deploy:
      placement:
        constraints: [node.role == manager]
  api:
    image: withinboredom/api:latest
    environment:
      - SMS
      - CALL
      - CALL_HOST
      - STRIPE_KEY
      - PLIVO_ID
      - PLIVO_TOKEN
      - DB_HOST
    volumes:
      - ./src/api:/app/api
      - api_modules:/app/api/node_modules
    depends_on:
      - rethunk
      - api-builder
    ports:
      - '1337:1337'
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints: [ node.role == worker ]
  engine-builder:
    image: withinboredom/composer:latest
    volumes:
      - ./src/engine:/var/www/html
      - engine_vendor:/var/www/html/vendor
    command: bash -c "cd /var/www/html && exec composer install"
  engine:
    image: withinboredom/engine:latest
    environment:
      - SMS
      - CALL
      - CALL_HOST
      - STRIPE_KEY
      - PLIVO_ID
      - PLIVO_TOKEN
    volumes:
      - ./src/engine:/var/www/html
      - engine_vendor:/var/www/html/vendor
    depends_on:
      - engine-builder
      - rethunk
    command: apache2-foreground
    ports:
      - '2200:80'
  web-builder:
    image: withinboredom/yarn:latest
    environment:
      - STRIPE_P_KEY
      - API_HOST
      - CALL
    volumes:
      - ./src/site:/app
      - node_modules:/app/js/node_modules
    command: bash -c "cd /app/js && yarn && node_modules/.bin/webpack -w"
  web:
    image: withinboredom/site:latest
    volumes:
      - ./src/site:/app
      - node_modules:/app/js/node_modules
    depends_on:
      - web-builder
    command: /caddy -conf /Caddyfile
    ports:
      - '8090:8080'
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
  rethunk:
    image: rethinkdb:latest
    ports:
      - '8080:8080'
      - '28015:28015'
    command: rethinkdb --bind all
volumes:
  api_modules:
  engine_vendor:
  node_modules:

networks:
  public:
  private: