version: '2'
services:
  api:
    image: quay.io/withinboredom/api:latest
    depends_on:
      - rethunk
    ports:
      - '1337:1337'
  engine:
    image: quay.io/withinboredom/engine:latest
    depends_on:
      - rethunk
    ports:
      - '2200:80'
  web:
    image: quay.io/withinboredom/site:latest
    ports:
      - '8090:8080'
  rethunk:
    image: rethinkdb:latest
    ports:
      - '9000:8080'
