version: '2'
services:
  api:
    build:
      dockerfile: ./images/php/Dockerfile
      context: ./
    volumes:
      - ./src/api:/app
      - vendor:/app/vendor
    command: bash -c "composer install && /app/vendor/amphp/aerys/bin/aerys -c /app/index.php"
  web:
    build:
      dockerfile: ./images/caddy/Dockerfile
      context: ./
    volumes:
      - ./src/site:/app
      - /app/js/node_modules
    ports:
      - '8090:8080'
volumes:
  vendor: