version: '2'
services:
  api:
    image: quay.io/withinboredom/api:latest
    depends_on:
      - rethunk
    volumes:
      - ./src/api:/app
      - api_vendor:/app/vendor
    command: bash -c "cd /app && ls -lah /app/vendor && exit && composer install && exec /app/vendor/amphp/aerys/bin/aerys -c /app/index.php"
    ports:
      - '1337:1337'
  engine-builder:
    image: quay.io/withinboredom/composer:latest
    volumes:
      - ./src/engine:/var/www/html
      - engine_vendor:/var/www/html/vendor
    command: bash -c "cd /var/www/html && composer install"
  engine:
    image: quay.io/withinboredom/engine:latest
    extends: engine-builder
    depends_on:
      - engine-builder
      - rethunk
    command: apache2-foreground
    ports:
      - '2200:80'
  web:
    image: quay.io/withinboredom/site:latest
    volumes:
      - ./src/site:/app
      - node_modules:/app/js/node_modules
    ports:
      - '8090:8080'
  rethunk:
    image: rethinkdb:latest
    ports:
      - '9000:8080'
volumes:
  api_vendor:
  engine_vendor:
  node_modules: