version: '2'
services:
  api-builder:
    image: withinboredom/composer:latest
    volumes:
      - ./src/api:/app
      - api_vendor:/app/vendor
    command: bash -c "cd /app && exec composer install"
  api:
    image: quay.io/withinboredom/api:latest
    extends: api-builder
    depends_on:
      - rethunk
      - api-builder
    command: bash -c "cd /app && exec /app/vendor/amphp/aerys/bin/aerys -c /app/index.php"
    ports:
      - '1337:1337'
  engine-builder:
    image: withinboredom/composer:latest
    volumes:
      - ./src/engine:/var/www/html
      - engine_vendor:/var/www/html/vendor
    command: bash -c "cd /var/www/html && exec composer install"
  engine:
    image: quay.io/withinboredom/engine:latest
    extends: engine-builder
    depends_on:
      - engine-builder
      - rethunk
    command: apache2-foreground
    ports:
      - '2200:80'
  web-builder:
    image: withinboredom/yarn:latest
    volumes:
      - ./src/site:/app
      - node_modules:/app/js/node_modules
    command: bash -c "cd /app/js && yarn && node_modules/.bin/webpack"
  web:
    image: quay.io/withinboredom/site:latest
    extends: web-builder
    depends_on:
      - web-builder
    command: /caddy -conf /Caddyfile
    ports:
      - '8090:8080'
  rethunk:
    image: rethinkdb:latest
    ports:
      - '9000:8080'
volumes:
  api_vendor:
  engine_vendor:
  node_modules: