version: '2'
services:
  api:
    build:
      dockerfile: ./images/php/Dockerfile
      context: ./
    volumes:
      - ./src/api:/app
      - vendor:/app/vendor
    command: bash -c "composer install && /app/vendor/amphp/aerys/bin/aerys -c /app/index.php"
    ports:
      - '1337:1337'
  web:
    build:
      dockerfile: ./images/caddy/Dockerfile
      context: ./
    volumes:
      - ./src/site:/app
      - node_modules:/app/js/node_modules
    ports:
      - '8090:8080'
  builder:
    build:
      dockerfile: ./images/builder/Dockerfile
      context: ./
    tty: true
    volumes:
      - ./src/site:/app
      - node_modules:/app/js/node_modules
    working_dir: /app/js
    command: bash -c "ls && yarn && node_modules/.bin/webpack -w"
  rethunk:
    image: rethinkdb:latest
    ports:
      - '9000:8080'
volumes:
  vendor:
  node_modules: